apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          readOnly: true
          name: nginx-main-conf-test
          subPath: nginx.conf
      volumes:
      - name: nginx-main-conf-test
        configMap:
          name: nginx-conf
          items:
            - key: nginx-main.conf
              path: nginx.conf
